apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: microservice-demo
  labels:
    app: project
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
      protocol: TCP
  selector:
    app: project
