namespace: ns-491
resources:
  - resources/ingress.yaml
  - resources/migration-notes.yaml
  - resources/prometheus-config.yaml
  - resources/secrets.yaml
  - resources/services.yaml
  - resources/storage.yaml
  - resources/workloads.yaml
