apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservice-demo
type: Opaque
stringData:
  PROJECT_DB_URI: mysql+mysqldb://root:password@mysql:3306/microservice-project
  TASK_DB_URI: postgres://postgres:password@postgresql:5432/microservice-task
  MYSQL_ROOT_PASSWORD: password
  POSTGRES_PASSWORD: password
