apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: account-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: account-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-api
    spec:
      containers:
        - name: account-api
          image: ralfx22/rrb-account-api
          env:
            - name: spring.cloud.config.uri
              value: http://config-server:8888/config-server
            - name: spring.profiles.active
              value: docker
