apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-api-postgres-data
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: transaction-api-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
