apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: wger
  labels:
    app.kubernetes.io/part-of: wger
data:
  redis.conf: |
    # === PLACEHOLDER: replace with your production redis.conf ===
    bind 0.0.0.0
    port 6379
    save 900 1
    save 300 10
    save 60 10000
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
