apiVersion: v1
kind: Service
metadata:
  name: celery-beat
  namespace: wger
  labels:
    app.kubernetes.io/name: celery-beat
    app.kubernetes.io/part-of: wger
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: celery-beat
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: placeholder
