apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: wger
  labels:
    app.kubernetes.io/part-of: wger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
