apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: wger
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: wger
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
