version: '2'
services:
  quotes:
    build:
      context: ./QuoteService
      dockerfile: app.dockerfile
    image: ralfx22/sme-quotes:v2
  api:
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    image: ralfx22/sme-api:v2
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./FrontendApplication
      dockerfile: app.dockerfile
    image: ralfx22/sme-frontend:v2
    ports:
      - "8080:80"
    