apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-grafana-volume
  namespace: bookstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-grafana
  namespace: bookstore
  labels:
    app: bookstore-grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bookstore-grafana
  template:
    metadata:
      labels:
        app: bookstore-grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: bookstore-grafana
          image: ralfx22/bsa-grafana:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: bookstore-grafana-volume
              subPath: data
      volumes:
        - name: bookstore-grafana-volume
          persistentVolumeClaim:
            claimName: bookstore-grafana-volume
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-grafana
  namespace: bookstore
spec:
  type: ClusterIP
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3000
  selector:
    app: bookstore-grafana
