apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-telegraf
  namespace: bookstore
  labels:
    app: bookstore-telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-telegraf
  template:
    metadata:
      labels:
        app: bookstore-telegraf
    spec:
      containers:
        - name: bookstore-telegraf
          image: ralfx22/bsa-telegraf:latest
          env:
            - name: HOSTNAME
              value: "bookstore-telegraf"
          ports:
            - containerPort: 8125
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-telegraf
  namespace: bookstore
spec:
  type: ClusterIP
  ports:
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    app: bookstore-telegraf
