apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-kapacitor
  namespace: bookstore
  labels:
    app: bookstore-kapacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-kapacitor
  template:
    metadata:
      labels:
        app: bookstore-kapacitor
    spec:
      containers:
        - name: bookstore-kapacitor
          image: kapacitor:1.7
          env:
            - name: KAPACITOR_HOSTNAME
              value: "bookstore-kapacitor"
            - name: KAPACITOR_INFLUXDB_0_URLS_0
              value: "http://bookstore-influxdb:8086"
          ports:
            - containerPort: 9092
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-kapacitor
  namespace: bookstore
spec:
  type: ClusterIP
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    app: bookstore-kapacitor
