apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api-postgres
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: transaction-api-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transaction-api-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transaction-api-postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: transaction-api-postgres
          image: postgres:15.2
          envFrom:
            - secretRef:
                name: transaction-api-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transaction-api-postgres-data
