apiVersion: v1
kind: Service
metadata:
  name: notification-api
  namespace: rrb-app
  labels:
    app: notification-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: notification-api
