namespace: ns-434
resources:
  - resources/account-api-deployment.yaml
  - resources/account-api-mongo-pvc.yaml
  - resources/account-api-mongo-service.yaml
  - resources/account-api-mongo-statefulset.yaml
  - resources/api-gateway-deployment.yaml
  - resources/api-gateway-ingress.yaml
  - resources/api-gateway-service.yaml
  - resources/asset-management-api-deployment.yaml
  - resources/asset-management-api-mysql-pvc.yaml
  - resources/asset-management-api-mysql-secret.yaml
  - resources/asset-management-api-mysql-service.yaml
  - resources/asset-management-api-mysql-statefulset.yaml
  - resources/config-server-deployment.yaml
  - resources/config-server-service.yaml
  - resources/discovery-server-deployment.yaml
  - resources/discovery-server-service.yaml
  - resources/grafana-deployment.yaml
  - resources/grafana-pvc.yaml
  - resources/grafana-secret.yaml
  - resources/grafana-service.yaml
  - resources/migration-notes-configmap.yaml
  - resources/notification-api-deployment.yaml
  - resources/notification-api-kafka-deployment.yaml
  - resources/notification-api-kafka-service.yaml
  - resources/prometheus-deployment.yaml
  - resources/prometheus-service.yaml
  - resources/redis-deployment.yaml
  - resources/redis-service.yaml
  - resources/transaction-api-deployment.yaml
  - resources/transaction-api-postgres-pvc.yaml
  - resources/transaction-api-postgres-secret.yaml
  - resources/transaction-api-postgres-service.yaml
  - resources/transaction-api-postgres-statefulset.yaml
  - resources/zipkin-deployment.yaml
  - resources/zipkin-service.yaml
