apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
  name: quotes
  namespace: sme-app
spec:
  type: ClusterIP
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: quotes
