apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-383.yml -o k8s-383/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: asset-management-api-mysql
  name: asset-management-api-mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
    - name: 3306-tcp
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: asset-management-api-mysql
