apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-db-volume
  namespace: bookstore
  labels:
    app: bookstore-mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-graphana-volume
  namespace: bookstore
  labels:
    app: bookstore-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booksture-influxdb-volume
  namespace: bookstore
  labels:
    app: bookstore-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booksture-chronograf-volume
  namespace: bookstore
  labels:
    app: bookstore-chronograf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
