apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: task
  name: task
spec:
  containers:
    - command:
        - ./init
      env:
        - name: DB_URI
          value: postgres://postgres:password@postgresql:5432/microservice-task
        - name: PROJECT_ADDRESS
          value: project:50052
        - name: USER_ADDRESS
          value: user:50051
      image: ralfx22/md-task
      name: task
      ports:
        - containerPort: 50053
          protocol: TCP
  restartPolicy: OnFailure
