apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: project
  name: project
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 50052
  selector:
    io.kompose.service: project
