apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ralfx22/md-api
          args: ["serve"]
          ports:
            - containerPort: 50059
          env:
            - name: USER_ADDRESS
              value: user:8080
            - name: PROJECT_ADDRESS
              value: project:8081
            - name: TASK_ADDRESS
              value: task:8082
