apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booksture-chronograf-volume
  namespace: bookstore
  labels:
    app: bookstore-chronograf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
