apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-db-volume
  namespace: bookstore
  labels:
    app: bookstore-mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
