apiVersion: v1
kind: Service
metadata:
  name: bookstore-zuul-api-gateway-server
  namespace: bookstore
  labels:
    app: bookstore-zuul-api-gateway-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8765
      targetPort: 8765
      protocol: TCP
  selector:
    app: bookstore-zuul-api-gateway-server
