apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: wger
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: wger
spec:
  serviceName: db-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/part-of: wger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/part-of: wger
    spec:
      securityContext:
        fsGroup: 70
      containers:
        - name: db
          image: docker.io/postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "wger"
            - name: POSTGRES_DB
              value: "wger"
            - name: TZ
              value: "Europe/Berlin"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
