apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bookstore-chronograf
  name: bookstore-chronograf
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: bookstore-chronograf
