apiVersion: v1
kind: Secret
metadata:
  name: asset-management-api-mysql-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_PASSWORD: pwd
  MYSQL_ROOT_PASSWORD: pwd
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: default
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: transaction-api-postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin
