apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sme-app
  labels:
    app: api
    io.kompose.service: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - name: api
          image: ralfx22/sme-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quotes:5000"
