apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f 468/docker-compose.yml -o 468-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notification-api-kafka
  name: notification-api-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: notification-api-kafka
