apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: wger
  labels:
    app.kubernetes.io/part-of: wger
data:
  default.conf: |
    upstream wger {
        server web:8000;
    }

    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /wger/static/;
        }

        location /media/ {
            alias /wger/media/;
        }

        location /health {
            access_log off;
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location / {
            proxy_pass http://wger;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }
