apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: wger
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: wger
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
