namespace: ns-307
resources:
  - resources/api-deployment.yaml
  - resources/api-service.yaml
  - resources/frontend-deployment.yaml
  - resources/frontend-ingress.yaml
  - resources/frontend-service.yaml
  - resources/migration-notes.yaml
  - resources/quotes-deployment.yaml
  - resources/quotes-service.yaml
