apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: app
  labels:
    io.kompose.service: quotes
    app: quotes
  annotations:
    kompose.cmd: kompose convert -f docker-compose-150.yml -o k8s-150/
    kompose.version: "1.34.0 (cbf2835db)"
spec:
  type: ClusterIP
  selector:
    app: quotes
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      protocol: TCP
