apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: sme-app
  labels:
    io.kompose.service: quotes
    app: quotes
  annotations:
    kompose.cmd: kompose convert -f docker-compose-310.yml -o k8s-310/
    kompose.version: "1.34.0 (cbf2835db)"
spec:
  type: ClusterIP
  selector:
    io.kompose.service: quotes
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      protocol: TCP
