apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-api-mongo
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: account-api-mongo
spec:
  serviceName: account-api-mongo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: account-api-mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-api-mongo
    spec:
      containers:
        - name: account-api-mongo
          image: mongo:6.0.5
          ports:
            - containerPort: 27017
              name: mongo
              protocol: TCP
          volumeMounts:
            - name: account-api-mongo-data
              mountPath: /data/db
      volumes:
        - name: account-api-mongo-data
          persistentVolumeClaim:
            claimName: account-api-mongo-data
