apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-management-api-mysql-data
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: asset-management-api-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
