apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  containers:
    - env:
        - name: POSTGRES_DB
          value: microservice-task
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
      image: postgres:16
      livenessProbe:
        exec:
          command:
            - pg_isready -U postgres -d microservice-task
        failureThreshold: 20
        periodSeconds: 5
        timeoutSeconds: 5
      name: postgresql
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
  restartPolicy: Never
  volumes:
    - name: postgresdb
      persistentVolumeClaim:
        claimName: postgresdb
