apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: rrb-app
  labels:
    app: discovery-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: discovery-server
