apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quotes
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: sme-app
        app.kubernetes.io/name: quotes
    spec:
      containers:
        - name: quotes
          image: ralfx22/sme-quotes:v2
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: quotes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quotes
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: sme-app
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: ralfx22/sme-api:v2
          env:
            - name: QUOTES_API
              value: http://quotes:5000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: sme-app
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          image: ralfx22/sme-frontend:v2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sme-app
  labels:
    app.kubernetes.io/part-of: sme-app
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
