apiVersion: v1
kind: ConfigMap
metadata:
  name: rrb-app-config
  namespace: rrb-app
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_CLOUD_CONFIG_URI: http://config-server:8888/config-server
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: TRACE
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: rrb-app
type: Opaque
stringData:
  MYSQL_DATABASE: mysql
  MYSQL_USER: admin
  MYSQL_PASSWORD: pwd
  MYSQL_ROOT_PASSWORD: pwd
  POSTGRES_DB: postgres
  POSTGRES_USER: root
  POSTGRES_PASSWORD: admin
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password
