apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-380.yml -o k8s-380/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: account-api-mongo
  name: account-api-mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: account-api-mongo
