apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sme-app
  labels:
    io.kompose.service: frontend
    app: frontend
spec:
  type: ClusterIP
  selector:
    io.kompose.service: frontend
  ports:
    - name: http-8080
      port: 8080
      targetPort: 80
      protocol: TCP
