apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f 433-docker-compose.yml -o 433-k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin
