apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: microservice-demo
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 50052
  selector:
    app: project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: microservice-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: project
          image: ralfx22/md-project
          env:
            - name: DB_URI
              value: mysql+mysqldb://root:password@mysql:3306/microservice-project
          ports:
            - containerPort: 50052
              protocol: TCP
