apiVersion: v1
kind: Secret
metadata:
  name: transaction-api-postgres-secret
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: transaction-api-postgres
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: root
  POSTGRES_PASSWORD: admin
