namespace: ns-613
resources:
  - resources/bookstore-account-service-deployment.yaml
  - resources/bookstore-account-service-service.yaml
  - resources/bookstore-billing-service-deployment.yaml
  - resources/bookstore-billing-service-service.yaml
  - resources/bookstore-catalog-service-deployment.yaml
  - resources/bookstore-catalog-service-service.yaml
  - resources/bookstore-chronograf-deployment.yaml
  - resources/bookstore-chronograf-service.yaml
  - resources/bookstore-consul-discovery-deployment.yaml
  - resources/bookstore-consul-discovery-service.yaml
  - resources/bookstore-db-volume-persistentvolumeclaim.yaml
  - resources/bookstore-frontend-deployment.yaml
  - resources/bookstore-frontend-ingress.yaml
  - resources/bookstore-frontend-service.yaml
  - resources/bookstore-grafana-deployment.yaml
  - resources/bookstore-grafana-service.yaml
  - resources/bookstore-graphana-volume-persistentvolumeclaim.yaml
  - resources/bookstore-influxdb-deployment.yaml
  - resources/bookstore-influxdb-service.yaml
  - resources/bookstore-kapacitor-deployment.yaml
  - resources/bookstore-kapacitor-service.yaml
  - resources/bookstore-mysql-db-deployment.yaml
  - resources/bookstore-mysql-db-service.yaml
  - resources/bookstore-order-service-deployment.yaml
  - resources/bookstore-order-service-service.yaml
  - resources/bookstore-payment-service-deployment.yaml
  - resources/bookstore-payment-service-service.yaml
  - resources/bookstore-prometheus-deployment.yaml
  - resources/bookstore-prometheus-service.yaml
  - resources/bookstore-telegraf-deployment.yaml
  - resources/bookstore-telegraf-service.yaml
  - resources/bookstore-zipkin-deployment.yaml
  - resources/bookstore-zipkin-service.yaml
  - resources/bookstore-zuul-api-gateway-server-deployment.yaml
  - resources/bookstore-zuul-api-gateway-server-ingress.yaml
  - resources/bookstore-zuul-api-gateway-server-service.yaml
  - resources/booksture-chronograf-volume-persistentvolumeclaim.yaml
  - resources/booksture-influxdb-volume-persistentvolumeclaim.yaml
  - resources/migration-notes.yaml
  - resources/mysql-secret.yaml
  - resources/namespace.yaml
