namespace: ns-419
resources:
  - resources/app-config-secret.yaml
  - resources/ingress.yaml
  - resources/migration-notes.yaml
  - resources/prometheus-config.yaml
  - resources/services.yaml
  - resources/storage.yaml
  - resources/workloads.yaml
