apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: microservice-demo
  labels:
    app: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: Microservice-demo-user
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - 'db.runCommand({ ping: 1 }).ok'
            failureThreshold: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - 'db.runCommand({ ping: 1 }).ok'
            periodSeconds: 5
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
              subPath: db
            - mountPath: /data/configdb
              name: mongodb-config
              subPath: configdb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
        - name: mongodb-config
          persistentVolumeClaim:
            claimName: mongodb-config
