apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config
  namespace: microservice-demo
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
