apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: microservice-demo
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: microservice-project
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -ppassword
            failureThreshold: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -ppassword
            periodSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb
              subPath: mysql
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysqldb
