apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb
  namespace: microservice-demo
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
