apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-api-mongo-data
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: account-api-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
