namespace: ns-509
resources:
  - resources/app-config.yaml
  - resources/ingress.yaml
  - resources/migration-notes.yaml
  - resources/namespace.yaml
  - resources/services.yaml
  - resources/storage.yaml
  - resources/workloads.yaml
