apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f 457-docker-compose.yml -o 457-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
    - name: 8761-tcp
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: discovery-server
