apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-api-mongo-claim0
  namespace: rrb-app
  labels:
    io.kompose.service: account-api-mongo-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-management-api-mysql-claim0
  namespace: rrb-app
  labels:
    io.kompose.service: asset-management-api-mysql-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim0
  namespace: rrb-app
  labels:
    io.kompose.service: grafana-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-api-postgres-claim0
  namespace: rrb-app
  labels:
    io.kompose.service: transaction-api-postgres-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: asset-management-api-mysql-secret
  namespace: rrb-app
type: Opaque
stringData:
  MYSQL_DATABASE: mysql
  MYSQL_USER: admin
  MYSQL_PASSWORD: pwd
  MYSQL_ROOT_PASSWORD: pwd
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: rrb-app
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: transaction-api-postgres-secret
  namespace: rrb-app
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: root
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: rrb-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
