apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: microservices-demo
spec:
  type: ClusterIP
  ports:
    - name: "8081"
      port: 8081
      targetPort: 50052
  selector:
    app: project
