apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f 424-docker-compose.yml -o 424-k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: account-api
  name: account-api
spec:
  containers:
    - env:
        - name: spring.cloud.config.uri
          value: http://config-server:8888/config-server
        - name: spring.profiles.active
          value: docker
      image: ralfx22/rrb-account-api
      name: account-api
  restartPolicy: OnFailure
