apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
  labels:
    io.kompose.service: frontend
    app: frontend
  annotations:
    kompose.cmd: kompose convert -f docker-compose-150.yml -o k8s-150/
    kompose.version: "1.34.0 (cbf2835db)"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ralfx22/sme-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
