apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: sme-app
  labels:
    io.kompose.service: api
    app: api
spec:
  type: ClusterIP
  selector:
    io.kompose.service: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
