apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: sme-app
  labels:
    io.kompose.service: quotes
    app: quotes
  annotations:
    created-by: migration-agent
spec:
  type: ClusterIP
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    io.kompose.service: quotes
