apiVersion: v1
kind: Service
metadata:
  name: bookstore-prometheus
  namespace: bookstore
  labels:
    app: bookstore-prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: bookstore-prometheus
