apiVersion: v1
kind: Service
metadata:
  name: account-api-mongo
  namespace: rrb-app
  labels:
    io.kompose.service: account-api-mongo
spec:
  type: ClusterIP
  selector:
    io.kompose.service: account-api-mongo
  ports:
    - name: tcp-27017
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rrb-app
  labels:
    io.kompose.service: api-gateway
spec:
  type: ClusterIP
  selector:
    io.kompose.service: api-gateway
  ports:
    - name: tcp-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: asset-management-api-mysql
  namespace: rrb-app
  labels:
    io.kompose.service: asset-management-api-mysql
spec:
  type: ClusterIP
  selector:
    io.kompose.service: asset-management-api-mysql
  ports:
    - name: tcp-3306
      port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: rrb-app
  labels:
    io.kompose.service: config-server
spec:
  type: ClusterIP
  selector:
    io.kompose.service: config-server
  ports:
    - name: tcp-8888
      port: 8888
      targetPort: 8888
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: rrb-app
  labels:
    io.kompose.service: discovery-server
spec:
  type: ClusterIP
  selector:
    io.kompose.service: discovery-server
  ports:
    - name: tcp-8761
      port: 8761
      targetPort: 8761
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: rrb-app
  labels:
    io.kompose.service: grafana
spec:
  type: ClusterIP
  selector:
    io.kompose.service: grafana
  ports:
    - name: tcp-3000
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-api-kafka
  namespace: rrb-app
  labels:
    io.kompose.service: notification-api-kafka
spec:
  type: ClusterIP
  selector:
    io.kompose.service: notification-api-kafka
  ports:
    - name: tcp-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: rrb-app
  labels:
    io.kompose.service: prometheus
spec:
  type: ClusterIP
  selector:
    io.kompose.service: prometheus
  ports:
    - name: tcp-9090
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rrb-app
  labels:
    io.kompose.service: redis
spec:
  type: ClusterIP
  selector:
    io.kompose.service: redis
  ports:
    - name: tcp-6379
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-api-postgres
  namespace: rrb-app
  labels:
    io.kompose.service: transaction-api-postgres
spec:
  type: ClusterIP
  selector:
    io.kompose.service: transaction-api-postgres
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: rrb-app
  labels:
    io.kompose.service: zipkin
spec:
  type: ClusterIP
  selector:
    io.kompose.service: zipkin
  ports:
    - name: tcp-9411
      port: 9411
      targetPort: 9411
      protocol: TCP
