apiVersion: v1
kind: Secret
metadata:
  name: bookstore-mysql-db-secret
  namespace: bookstore
type: Opaque
stringData:
  MYSQL_DATABASE: bookstore_db
  MYSQL_USER: bookstoreDBA
  MYSQL_PASSWORD: PaSSworD
  MYSQL_ROOT_PASSWORD: r00tPaSSworD
