apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim0
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
