apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-server
    spec:
      containers:
        - name: config-server
          image: ralfx22/rrb-config-server
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          env:
            - name: spring.profiles.active
              value: docker
