apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: rrb-app
  labels:
    app: asset-management-api-mysql
type: Opaque
stringData:
  MYSQL_DATABASE: mysql
  MYSQL_USER: admin
  MYSQL_PASSWORD: pwd
  MYSQL_ROOT_PASSWORD: pwd
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: rrb-app
  labels:
    app: transaction-api-postgres
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: root
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: rrb-app
  labels:
    app: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password
