namespace: ns-563
resources:
  - resources/account-api-deployment.yaml
  - resources/account-api-mongo-deployment.yaml
  - resources/account-api-mongo-pvc.yaml
  - resources/account-api-mongo-service.yaml
  - resources/account-api-service.yaml
  - resources/api-gateway-deployment.yaml
  - resources/api-gateway-ingress.yaml
  - resources/api-gateway-service.yaml
  - resources/asset-management-api-deployment.yaml
  - resources/asset-management-api-mysql-deployment.yaml
  - resources/asset-management-api-mysql-pvc.yaml
  - resources/asset-management-api-mysql-service.yaml
  - resources/asset-management-api-service.yaml
  - resources/config-server-configmap.yaml
  - resources/config-server-deployment.yaml
  - resources/config-server-service.yaml
  - resources/db-secrets.yaml
  - resources/discovery-server-deployment.yaml
  - resources/discovery-server-service.yaml
  - resources/grafana-deployment.yaml
  - resources/grafana-pvc.yaml
  - resources/grafana-service.yaml
  - resources/migration-notes.yaml
  - resources/namespace.yaml
  - resources/notification-api-deployment.yaml
  - resources/notification-api-kafka-deployment.yaml
  - resources/notification-api-kafka-service.yaml
  - resources/notification-api-service.yaml
  - resources/prometheus-configmap.yaml
  - resources/prometheus-deployment.yaml
  - resources/prometheus-service.yaml
  - resources/redis-deployment.yaml
  - resources/redis-service.yaml
  - resources/transaction-api-deployment.yaml
  - resources/transaction-api-postgres-deployment.yaml
  - resources/transaction-api-postgres-pvc.yaml
  - resources/transaction-api-postgres-service.yaml
  - resources/transaction-api-service.yaml
  - resources/zipkin-deployment.yaml
  - resources/zipkin-service.yaml
