apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booksture-influxdb-volume
  namespace: bookstore
  labels:
    app: bookstore-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
