apiVersion: v1
kind: Service
metadata:
  name: notification-api-kafka
  namespace: rrb-app
  labels:
    app: notification-api-kafka
spec:
  type: ClusterIP
  ports:
    - name: host
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: plaintext
      port: 29092
      targetPort: 29092
      protocol: TCP
  selector:
    app: notification-api-kafka
