namespace: ns-379
resources:
  - resources/account-api.yaml
  - resources/api-gateway.yaml
  - resources/asset-management-api.yaml
  - resources/config-server.yaml
  - resources/discovery-server.yaml
  - resources/grafana.yaml
  - resources/migration-notes.yaml
  - resources/notification-api.yaml
  - resources/prometheus.yaml
  - resources/redis.yaml
  - resources/transaction-api.yaml
  - resources/zipkin.yaml
