apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: sme-app
  labels:
    io.kompose.service: quotes
    app: quotes
  annotations:
    note: "Service added to restore in-cluster DNS for api -> http://quotes:5000"
spec:
  type: ClusterIP
  selector:
    io.kompose.service: quotes
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      protocol: TCP
