apiVersion: v1
kind: Secret
metadata:
  name: asset-management-mysql-secret
  namespace: microservices
  labels:
    app: asset-management-api-mysql
stringData:
  MYSQL_DATABASE: "mysql"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "pwd"
  MYSQL_ROOT_PASSWORD: "pwd"
---
apiVersion: v1
kind: Secret
metadata:
  name: transaction-postgres-secret
  namespace: microservices
  labels:
    app: transaction-api-postgres
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: microservices
  labels:
    app: grafana
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "password"
