apiVersion: v1
kind: Pod
metadata:
  name: transaction-api
  namespace: microservices
  labels:
    io.kompose.service: transaction-api
spec:
  containers:
    - env:
        - name: spring.cloud.config.uri
          value: http://config-server:8888/config-server
        - name: spring.profiles.active
          value: docker
      image: 0145136798/transaction-api
      name: transaction-api
  restartPolicy: OnFailure
