apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-api-postgres-claim0
  namespace: microservices
  labels:
    io.kompose.service: transaction-api-postgres-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
