namespace: ns-372
resources:
  - resources/account-api-deployment.yaml
  - resources/account-api-mongo-claim0-persistentvolumeclaim.yaml
  - resources/account-api-mongo-deployment.yaml
  - resources/account-api-mongo-service.yaml
  - resources/api-gateway-deployment.yaml
  - resources/api-gateway-ingress.yaml
  - resources/api-gateway-service.yaml
  - resources/asset-management-api-deployment.yaml
  - resources/asset-management-api-mysql-claim0-persistentvolumeclaim.yaml
  - resources/asset-management-api-mysql-deployment.yaml
  - resources/asset-management-api-mysql-service.yaml
  - resources/config-server-deployment.yaml
  - resources/config-server-service.yaml
  - resources/discovery-server-deployment.yaml
  - resources/discovery-server-service.yaml
  - resources/grafana-claim0-persistentvolumeclaim.yaml
  - resources/grafana-deployment.yaml
  - resources/grafana-service.yaml
  - resources/migration-notes.yaml
  - resources/notification-api-deployment.yaml
  - resources/notification-api-kafka-deployment.yaml
  - resources/notification-api-kafka-service.yaml
  - resources/prometheus-claim0-persistentvolumeclaim.yaml
  - resources/prometheus-deployment.yaml
  - resources/prometheus-service.yaml
  - resources/redis-deployment.yaml
  - resources/redis-service.yaml
  - resources/secret-asset-management-mysql.yaml
  - resources/secret-grafana.yaml
  - resources/secret-transaction-postgres.yaml
  - resources/transaction-api-deployment.yaml
  - resources/transaction-api-postgres-claim0-persistentvolumeclaim.yaml
  - resources/transaction-api-postgres-deployment.yaml
  - resources/transaction-api-postgres-service.yaml
  - resources/zipkin-deployment.yaml
  - resources/zipkin-service.yaml
