---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: sme-app
  labels:
    io.kompose.service: api
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    io.kompose.service: api
