namespace: ns-443
resources:
  - resources/ingress.yaml
  - resources/migration-notes.yaml
  - resources/persistentvolumeclaims.yaml
  - resources/secrets.yaml
  - resources/services.yaml
  - resources/workloads.yaml
