apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bookstore-order-service
  name: bookstore-order-service
spec:
  ports:
    - name: "7001"
      port: 7001
      targetPort: 7001
  selector:
    io.kompose.service: bookstore-order-service
