apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: microservice-demo
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50059
      targetPort: 50059
      protocol: TCP
  selector:
    app: api
