apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: microservice-demo
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: ralfx22/md-project
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PROJECT_DB_URI
          ports:
            - containerPort: 50052
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
