apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f 467/docker-compose.yml -o 467-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  containers:
    - env:
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
          value: TRACE
        - name: spring.cloud.config.uri
          value: http://config-server:8888/config-server
        - name: spring.profiles.active
          value: docker
      image: ralfx22/rrb-api-gateway
      name: api-gateway
      ports:
        - containerPort: 8080
          protocol: TCP
  restartPolicy: OnFailure
