apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: microservice-demo
type: Opaque
stringData:
  POSTGRES_DB: microservice-task
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: microservice-demo
type: Opaque
stringData:
  MYSQL_DATABASE: microservice-project
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: microservice-demo
type: Opaque
stringData:
  MONGO_INITDB_DATABASE: Microservice-demo-user
---
apiVersion: v1
kind: Secret
metadata:
  name: app-db-uris
  namespace: microservice-demo
type: Opaque
stringData:
  USER_DB_URI: "mongodb://mongo:27017/"
  PROJECT_DB_URI: "mysql+mysqldb://root:password@mysql:3306/microservice-project"
  TASK_DB_URI: "postgres://postgres:password@postgresql:5432/microservice-task"
