apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: microservice-demo
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: user
