apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: app
  labels:
    app: quotes
spec:
  clusterIP: None
  selector:
    app: quotes
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
