apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-api-mongo-claim0
  namespace: microservices
  labels:
    io.kompose.service: account-api-mongo-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
