apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-management-api-mysql-claim0
  namespace: microservices
  labels:
    io.kompose.service: asset-management-api-mysql-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
