apiVersion: v1
kind: Service
metadata:
  name: bookstore-consul-discovery
  namespace: bookstore
  labels:
    app: bookstore-consul-discovery
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      protocol: TCP
  selector:
    app: bookstore-consul-discovery
