apiVersion: v1
kind: Service
metadata:
  name: bookstore-zipkin
  namespace: bookstore
  labels:
    app: bookstore-zipkin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: bookstore-zipkin
