apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-api-mongo-claim0
  namespace: rrb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-management-api-mysql-claim0
  namespace: rrb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim0
  namespace: rrb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-api-postgres-claim0
  namespace: rrb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
