apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: rrb-app
  labels:
    io.kompose.service: discovery-server
spec:
  type: ClusterIP
  selector:
    io.kompose.service: discovery-server
  ports:
    - name: eureka
      port: 8761
      targetPort: 8761
