apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim0
  namespace: rrb-app
  labels:
    io.kompose.service: grafana-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
