apiVersion: v1
kind: Secret
metadata:
  name: asset-management-mysql-secret
  namespace: rrb-app
type: Opaque
stringData:
  MYSQL_DATABASE: "mysql"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "pwd"
  MYSQL_ROOT_PASSWORD: "pwd"
