apiVersion: v1
kind: Service
metadata:
  name: transaction-api-postgres
  namespace: rrb-app
  labels:
    io.kompose.service: transaction-api-postgres
spec:
  type: ClusterIP
  selector:
    io.kompose.service: transaction-api-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
