apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservice-demo
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ralfx22/md-api
          imagePullPolicy: IfNotPresent
          args:
            - proxy
          env:
            - name: HOST
              value: api
            - name: PORT
              value: "8083"
            - name: PROXY_PORT
              value: "9090"
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
