apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb
  namespace: microservice-demo
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
