apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservice-demo
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: microservice-demo
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: grpc
      port: 8083
      targetPort: 50059
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: microservice-demo
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: grpc
      port: 8080
      targetPort: 50051
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: microservice-demo
  labels:
    app: project
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - name: grpc
      port: 8081
      targetPort: 50052
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: task
  namespace: microservice-demo
  labels:
    app: task
spec:
  type: ClusterIP
  selector:
    app: task
  ports:
    - name: grpc
      port: 8082
      targetPort: 50053
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: microservice-demo
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microservice-demo
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: microservice-demo
  labels:
    app: postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
      protocol: TCP
