apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-management-api-mysql
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: asset-management-api-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asset-management-api-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asset-management-api-mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: asset-management-api-mysql
          image: mysql:8.0.33
          args:
            - --default-authentication-plugin=mysql_native_password
            - --ignore-db-dir=lost+found
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: asset-management-api-mysql-data
