apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: account-api-mongo
  name: account-api-mongo
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-27017
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    io.kompose.service: account-api-mongo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: asset-management-api-mysql
  name: asset-management-api-mysql
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-3306
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    io.kompose.service: asset-management-api-mysql
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: config-server
  name: config-server
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-8888
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    io.kompose.service: config-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-8761
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    io.kompose.service: discovery-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-3000
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    io.kompose.service: grafana
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notification-api-kafka
  name: notification-api-kafka
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    io.kompose.service: notification-api-kafka
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: prometheus
  name: prometheus
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-9090
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    io.kompose.service: prometheus
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis
  name: redis
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-6379
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    io.kompose.service: redis
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transaction-api-postgres
  name: transaction-api-postgres
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    io.kompose.service: transaction-api-postgres
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: rrb-app
spec:
  type: ClusterIP
  ports:
    - name: tcp-9411
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    io.kompose.service: zipkin
