namespace: ns-377
resources:
  - resources/account-api-mongo.yaml
  - resources/account-api.yaml
  - resources/api-gateway.yaml
  - resources/asset-management-api-mysql.yaml
  - resources/asset-management-api.yaml
  - resources/config-server.yaml
  - resources/discovery-server.yaml
  - resources/grafana.yaml
  - resources/migration-notes.yaml
  - resources/notification-api-kafka.yaml
  - resources/notification-api.yaml
  - resources/prometheus.yaml
  - resources/redis.yaml
  - resources/transaction-api-postgres.yaml
  - resources/transaction-api.yaml
  - resources/zipkin.yaml
