apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: rrb-app
  labels:
    app.kubernetes.io/name: zipkin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: 9411
      protocol: TCP
