apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: wger
  labels:
    app.kubernetes.io/part-of: wger
type: Opaque
stringData:
  POSTGRES_USER: "wger"
  POSTGRES_PASSWORD: "wger"
  POSTGRES_DB: "wger"
