apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: microservice-demo
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: ralfx22/md-user
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_DB_URI
            - name: DB_NAME
              value: Microservice-demo-user
          ports:
            - containerPort: 50051
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
