apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f 458-docker-compose.yml -o 458-kompose/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transaction-api
  name: transaction-api
spec:
  containers:
    - env:
        - name: spring.cloud.config.uri
          value: http://config-server:8888/config-server
        - name: spring.profiles.active
          value: docker
      image: ralfx22/rrb-transaction-api
      name: transaction-api
  restartPolicy: OnFailure
