apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: quotes-app
  labels:
    app.kubernetes.io/name: api-config
    app.kubernetes.io/part-of: quotes-app
data:
  QUOTES_API: "http://quotes:5000"
