apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: rrb-app
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ralfx22/rrb-config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: spring.profiles.active
              value: docker
      restartPolicy: Always
