locals {
  common_tags = {
    ManagedBy = "terraform"
    Project   = "sme-app"
  }
}

# Acquire AZs
data "aws_availability_zones" "available" {
  state = "available"
}

# VPC via terraform-aws-modules/vpc/aws
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 6.6"

  name = "${var.cluster_name}-vpc"
  cidr = var.vpc_cidr

  azs             = slice(data.aws_availability_zones.available.names, 0, var.az_count)
  public_subnets  = [for i in range(var.az_count) : cidrsubnet(var.vpc_cidr, 8, i + 1)]
  private_subnets = [for i in range(var.az_count) : cidrsubnet(var.vpc_cidr, 8, i + 101)]

  enable_nat_gateway = true
  single_nat_gateway = true

  public_subnet_tags = merge(
    local.common_tags,
    {
      "kubernetes.io/role/elb" = "1"
      # The cluster name tag helps the ALB controller find subnets.
      "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    }
  )

  private_subnet_tags = merge(local.common_tags, { "kubernetes.io/cluster/${var.cluster_name}" = "shared" })

  tags = local.common_tags
}

# EKS cluster via terraform-aws-modules/eks/aws
resource "eks" "eks1" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 21.15"

  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version

  subnet_id = module.vpc.private_subnets
  vpc_id  = module.vpc.vpc_id

  # Managed node groups
  node_groups = {
    default = {
      desired_capacity = var.desired_node_count
      min_capacity     = 1
      max_capacity     = max(var.desired_node_count, 2)
      instance_types   = [var.node_instance_type]
      # Optional key_name if you want SSH access
      key_name = var.key_name != "" ? var.key_name : null
    }
  }

  # Enable OIDC provider for IRSA
  manage_aws_auth      = true
  enable_irsa          = true
  create_oidc_provider = true

  cluster_enabled_log_types = ["api", "audit", "authenticator"]

  tags = local.common_tags
}

# Waiter: ensure the data.aws_eks_cluster can find provider outputs
data "aws_eks_cluster" "post" {
  name       = module.eks.cluster_id
  depends_on = [module.eks]
}

# Find existing OIDC provider created for this cluster (created by module.eks when create_oidc_provider = true)
data "aws_iam_openid_connect_provider" "oidc" {
  url = replace(data.aws_eks_cluster.post.identity[0].oidc[0].issuer, "https://", "")
}

# Minimal IAM policy for AWS Load Balancer Controller (sufficient actions). Review for least-privilege if required.
resource "aws_iam_policy" "alb_controller" {
  name        = "${var.cluster_name}-aws-load-balancer-controller-policy"
  description = "Policy for AWS Load Balancer Controller (generated by Terraform)"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "acm:DescribeCertificate",
          "acm:ListCertificates",
          "acm:GetCertificate",
          "ec2:AuthorizeSecurityGroupIngress",
          "ec2:CreateSecurityGroup",
          "ec2:CreateTags",
          "ec2:DeleteTags",
          "ec2:DeleteSecurityGroup",
          "ec2:Describe*",
          "ec2:ModifyInstanceAttribute",
          "ec2:ModifyNetworkInterfaceAttribute",
          "ec2:RevokeSecurityGroupIngress",
          "elasticloadbalancing:*",
          "iam:CreateServiceLinkedRole",
          "iam:GetServerCertificate",
          "iam:ListServerCertificates",
          "cognito-idp:*",
          "waf-regional:*",
          "waf:*",
          "shield:*",
          "tag:GetResources",
          "tag:TagResources"
        ]
        Resource = "*"
      }
    ]
  })
}

# IAM role for the controller using IRSA (federated principal = cluster OIDC provider)
resource "aws_iam_role" "alb_controller" {
  name = "${var.cluster_name}-alb-controller-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Principal = {
          Federated = data.aws_iam_openid_connect_provider.oidc.arn
        }
        Action = "sts:AssumeRoleWithWebIdentity",
        Condition = {
          StringEquals = {
            # form: <issuer-without-https>:sub
            "${replace(data.aws_eks_cluster.post.identity[0].oidc[0].issuer, "https://", "")}:sub" = "system:serviceaccount:kube-system:aws-load-balancer-controller"
          }
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "alb_attach" {
  role       = aws_iam_role.alb_controller.name
  policy_arn = aws_iam_policy.alb_controller.arn
}

# Create Kubernetes ServiceAccount in kube-system namespace bound to IAM role (IRSA)
resource "kubernetes_service_account" "alb_sa" {
  metadata {
    name      = "aws-load-balancer-controller"
    namespace = "kube-system"
    annotations = {
      "eks.amazonaws.com/role-arn" = aws_iam_role.alb_controller.arn
    }
  }

  depends_on = [module.eks]
}

# Helm release for AWS Load Balancer Controller
resource "helm_release" "aws_load_balancer_controller" {
  name       = "aws-load-balancer-controller"
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  version    = "1.6.6" # pinned chart version; change if necessary
  namespace  = "kube-system"

  create_namespace = false

  # We use the serviceAccount created above via IRSA
  set {
    name  = "clusterName"
    value = var.cluster_name
  }

  set {
    name  = "serviceAccount.create"
    value = "false"
  }

  set {
    name  = "serviceAccount.name"
    value = kubernetes_service_account.alb_sa.metadata[0].name
  }

  # This must be applied after the ServiceAccount and cluster are ready
  depends_on = [kubernetes_service_account.alb_sa]
}
